eBookSaleProject/Controllers/AuthorController.cs
using eBookSaleProject.Data;
using eBookSaleProject.Data.Services;
using eBookSaleProject.Data.Static;
using eBookSaleProject.Models;
using eBookSaleProject.Models.PaginationModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace eBookSaleProject.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class AuthorController : Controller
    {
        private readonly IAuthorService authorService;

        public AuthorController(IAuthorService authorService)
        {
            this.authorService = authorService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(int pg = 1)
        {
          var allAuthors = await authorService.GetAllAsync();
            const int pageSize = 9;
            if (pg < 1)
            {
                pg = 1;
            }

            int rescCount = allAuthors.Count();

            var paginationModel = new PaginationModel(rescCount, pg, pageSize);

            int rescSkip = (pg - 1) * pageSize;

            var data = allAuthors.Skip(rescSkip).Take(paginationModel.PageSize).ToArray();
            this.ViewBag.PaginationModel = paginationModel;

            return View(data);
            //return View(allAuthors);

        }


        [AllowAnonymous]
        public async Task<FileResult> AuthorImage(int id)
        {

            Author author = await authorService.GetByIdAsync(id);
            if (author != null && author.Image?.Length > 0)
            {
                return File(author.Image, "image/jpeg", author.FullName + "-" + author.Id + ".jpg");
            }
            return null;
        }

        //Get:  Author/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }



        //Get:Author/Details/new{ id = author.id}
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var authorDetails = await authorService.GetByIdAsync(id);
            if(authorDetails == null)
            {
                return View(nameof(NotFound));
            }
            return View(authorDetails);
        }

        //Get: Author/Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var authorDetails = await authorService.GetByIdAsync(id);
            if (authorDetails == null) return View("NotFound");
            
            return View(authorDetails);

        }

        //Get: Author/Delete
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var author = await authorService.GetByIdAsync(id); 
            if(author==null)
            {
                return View(nameof(NotFound));
            }
            return View(author);
        }

        //Post: Author/Delete
        [HttpPost]
        public async Task<IActionResult> DeleteAuthor(int id)
        {
            var author = await authorService.GetByIdAsync(id);
            if(author == null)
            {
                return View(nameof(NotFound));
            }
            await authorService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        //Post: Author/Create
        [HttpPost]
        public async Task<IActionResult> Create(Author author, IFormFile ImageUpload)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }
            using(var stream =new MemoryStream())
            {
               await ImageUpload.CopyToAsync(stream);
                author.Image = stream.ToArray();
            }
            await authorService.AddAsync(author);
            return RedirectToAction(nameof(Index));
        }

        //Post: Author/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(int id,  Author author, IFormFile ImageUpload)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }
            if(ImageUpload != null)
            {
                using (var stream = new MemoryStream())
                {
                    await ImageUpload.CopyToAsync(stream);
                    author.Image = stream.ToArray();
                }
            }
            await authorService.UpdateAsync(id, author);
            return RedirectToAction("Index");
        }

        
    }
}

eBookSaleProject/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using eBookSaleProject.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using eBookSaleProject.Data.Services;
using eBookSaleProject.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using eBookSaleProject.Data.Static;
using System.IO;
using Microsoft.AspNetCore.Http;
using eBookSaleProject.Models.PaginationModel;

namespace eBookSaleProject.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class BookController : Controller
    {
        private readonly IBookService bookService;

        public BookController(IBookService bookService)
        {
            this.bookService = bookService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(int pg = 1)
        {
            var allBooks = await bookService.GetAllAsync(n => n.Publisher);

            const int pageSize = 9;
            if(pg < 1)
            {
                pg = 1;
            }

            int rescCount = allBooks.Count();

            var paginationModel = new PaginationModel(rescCount, pg, pageSize);

            int rescSkip = (pg - 1) * pageSize;

            var data = allBooks.Skip(rescSkip).Take(paginationModel.PageSize).ToArray();
            this.ViewBag.PaginationModel = paginationModel;
            //return View(allBooks);
            return View(data);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allBooks = await bookService.GetAllAsync(n => n.Publisher);
            if (!string.IsNullOrEmpty(searchString))
            {
                var filterResult = allBooks.Where(n=>n.Name.ToLower().Contains(searchString.ToLower())||
                n.Description.ToLower().Contains(searchString.ToLower() )
                ||n.BookCategory.ToString().ToLower().Contains(searchString.ToLower()));
                return View("Index",filterResult);
            }
            return View("Index",allBooks);
        }


        //Get: Details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var bookDetails = await bookService.GetBookByIdAsync(id);
            return View(bookDetails);
        }

        public async Task<IActionResult> Create()
        {
            var bookDropDownsData = await bookService.GetNewBookDropDownValues();
            ViewBag.AuthorsList = new SelectList(bookDropDownsData.Authors, "Id", "FullName");
            ViewBag.PublishersList = new SelectList(bookDropDownsData.Publishers, "Id", "Name");
            return View();
        }

        //Post: Delete 

        public async Task<IActionResult> Delete(int id)
        {
            var book = await bookService.GetBookByIdAsync(id);
            if(book == null)
            {
                return View(nameof(NotFound));
            }
            await bookService.DeleteAsync(id);
            return RedirectToAction("Index");
        }

        //Post: Create

        [HttpPost]
        public async Task<IActionResult> Create(BookViewModel bookViewModel, IFormFile ImageUpload,IFormFile BookFileUpload)
        {
            if (!ModelState.IsValid)
            {
                var bookDropDownsData = await bookService.GetNewBookDropDownValues();
                ViewBag.AuthorsList = new SelectList(bookDropDownsData.Authors, "Id", "FullName");
                ViewBag.PublishersList = new SelectList(bookDropDownsData.Publishers, "Id", "Name");
                return View(bookViewModel);
            }

            using (var stream = new MemoryStream())
            {
                await ImageUpload.CopyToAsync(stream);
                bookViewModel.Image = stream.ToArray();
            }

            using(var stream = new MemoryStream())
            {
                await BookFileUpload.CopyToAsync(stream);
                bookViewModel.BookFile = stream.ToArray();
            }

            await bookService.AddNewBookAsync(bookViewModel);

            return RedirectToAction(nameof(Index));
        }

        //Get: Edit
        public async Task<IActionResult> Edit(int id)
        {
            var bookDetails = await bookService.GetBookByIdAsync(id);
            if (bookDetails == null) return View("NotFound");

            var response = new BookViewModel()
            {
                Id = bookDetails.Id,
                Name = bookDetails.Name,
                Price = bookDetails.Price,
                Description = bookDetails.Description,
                Image = bookDetails.Image,
                BookFile = bookDetails.BookFile,
                EdititonDate = bookDetails.EdititonDate,
                BookCategory = bookDetails.BookCategory,
                PublisherId = bookDetails.PublisherId,
                AuthorIds = bookDetails.Author_Books.Select(n => n.AuthorId).ToList(),
            };

            var bookDropDownsData = await bookService.GetNewBookDropDownValues();
            ViewBag.AuthorsList = new SelectList(bookDropDownsData.Authors, "Id", "FullName");
            ViewBag.PublishersList = new SelectList(bookDropDownsData.Publishers, "Id", "Name");
            return View(response);
        }


        [AllowAnonymous]
        public async Task<FileResult> BookImage(int id)
        {

            Book book = await bookService.GetBookByIdAsync(id);
            if (book != null && book.Image?.Length > 0)
            {
                return File(book.Image, "image/jpeg", book.Name + "-" + book.Id + ".jpg");
            }
            return null;
        }


        [AllowAnonymous]
        public async Task<FileResult> BookFile(int id)
        {

            Book book = await bookService.GetBookByIdAsync(id);
            if (book != null && book.BookFile?.Length > 0)
            {
                return File(book.BookFile, "application/pdf", book.BookFile + "-" + book.Id + ".pdf");
            }
            return null;
        }


        //Post: Edit

        [HttpPost]
        public async Task<IActionResult> Edit(int id,BookViewModel bookViewModel, IFormFile ImageUpload, IFormFile BookFileUpload)
        {
            if(id != bookViewModel.Id)
            {
                return View(nameof(NotFound));
            }
            if (!ModelState.IsValid)
            {
                var bookDropDownsData = await bookService.GetNewBookDropDownValues();
                ViewBag.AuthorsList = new SelectList(bookDropDownsData.Authors, "Id", "FullName");
                ViewBag.PublishersList = new SelectList(bookDropDownsData.Publishers, "Id", "Name");
                return View(bookViewModel);
            }
            if (ImageUpload != null)
            {
                using (var stream = new MemoryStream())
                {
                    await ImageUpload.CopyToAsync(stream);
                    bookViewModel.Image = stream.ToArray();
                }
            }
            if(BookFileUpload != null)
            {
                using(var stream = new MemoryStream())
                {
                    await BookFileUpload.CopyToAsync(stream);
                    bookViewModel.BookFile = stream.ToArray();
                }
            }
            
            await bookService.UpdateBookAsync(bookViewModel);
            return RedirectToAction(nameof(Index));
        }

    }
}

eBookSaleProject/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using eBookSaleProject.Data.Services;
using eBookSaleProject.Data.Cart;
using eBookSaleProject.Data.ViewModels;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace eBookSaleProject.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IBookService bookService;
        private readonly ShoppingCart shoppingCart;
        private readonly IOrdersService ordersService;

        public OrdersController(IBookService bookService, ShoppingCart shoppingCart,IOrdersService ordersService)
        {
            this.bookService = bookService;
            this.shoppingCart = shoppingCart;
            this.ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await ordersService.GetOrdersByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }

        public async Task<IActionResult> MyBooks()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var books = await ordersService.GetOrderedBooksByUserIdAndRoleAsync(userId, userRole);
            return View(books);
        }

        public IActionResult ShoppingCart()
        {
            var items = shoppingCart.GetShoppingCartItems();
            shoppingCart.ShoppingCartItems = items;
            var response = new ShoppingCartViewModel()
            {
                ShoppingCart = shoppingCart,
                ShoppingCartTotal = shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item =await bookService.GetBookByIdAsync(id);
            if(item != null)
            {
                shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await bookService.GetBookByIdAsync(id);
            if (item != null)
            {
                shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = shoppingCart.GetShoppingCartItems();

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await  ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await shoppingCart.ClearShoppingCartAsync();
            shoppingCart.ShoppingCartItems = null;
            return View("OrderCompleted");
        }

    }
}

eBookSaleProject/Views/Shared/NotFound.cshtml
<div class="row text-center">
        <div class="col-md-6 offset-3">
            <h1 class="text-info">The item that you are looking for is not exist, or there are some errors with your search</h1>
                <hr />
             <a class="btn btn-outline-secondary"  asp-controller="Book" asp-action="Index">Home Page</a>
        </div>

</div>

eBookSaleProject/Views/Shared/_CreateItem.cshtml
@model string
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position:fixed; right:25px; bottom:70px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle"></i> Add New</a>
    </div>
}

eBookSaleProject/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>

    <span style="padding:3px"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
else
{
    <span style="padding:3px"></span>

    @*User Profile Section*@
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn"
                data-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>
            @if (User.IsInRole("Admin"))
            {
            <li>
                <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                    <i class="bi bi-people"></i> Users
                </a>
            </li>
            }
            @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Orders" asp-action="MyBooks">
                    <i class="bi bi-wallet-fill"></i> Purchased
                </a>
            </li>
            }
        </ul>
    </div>

    <span style="padding:3px"></span>

    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Logout
        </button>
    </form>
}

eBookSaleProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eBookSaleProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Book" asp-action="Index">
                    <div class="logo-image">
                         <img src="~/images/6.jpg"  width="50" alt="" class="d-inline-block align-middle mr-2"/>
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Book" asp-action="Index"><i class="bi bi-book"></i><b> Books</b></a>
                        </li>

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i><b> Management</b>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Author" asp-action="Index"><i class="bi bi-people-fill"></i> Authors</a>
                                    <a class="dropdown-item" asp-controller="Publisher" asp-action="Index"><i class="bi bi-person-lines-fill"></i> Publishers</a>
                                </div>
                            </li>
                         }


                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Book" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a book ...." /><span style="padding:2px"></span>
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                    <partial name="_Identity.cshtml"/>

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - eBookSaleProject 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

eBookSaleProject/Views/Shared/_Pagination.cshtml
@using eBookSaleProject.Models.PaginationModel
@{
    PaginationModel paginationModel = new PaginationModel();
    int pageNo = 0;
    if (ViewBag.PaginationModel != null)
    {
        paginationModel = ViewBag.PaginationModel;
        pageNo = paginationModel.CurrentPage;
    }
}
@model string

<div class="row justify-content-md-center" style="padding-top:10px">
        @if (paginationModel.TotalPages > 0)
        {
            <ul class="pagination justify-content-end">
                @if (paginationModel.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="@Model" asp-action="Index" asp-route="1">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="@Model" asp-action="Index" asp-route="@(paginationModel.CurrentPage-1)">Previous</a>
                    </li>
                }
                @for (var pge = paginationModel.StartPage; pge <= paginationModel.EndPage; pge++)
                {
                    <li class="page-item @(pge==paginationModel.CurrentPage?"active":"")">
                        <a class="page-link" asp-controller="@Model" asp-action="Index" asp-route-pg="@pge">@pge</a>
                    </li>
                }
                @if (paginationModel.CurrentPage < paginationModel.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="@Model" asp-action="Index" asp-route="@(paginationModel.CurrentPage+1)">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="@Model" asp-action="Index" asp-route="@(paginationModel.TotalPages)">Last</a>
                    </li>
                }
            </ul>
        }
</div>