eBookSaleProject/Models/Book.cs
using eBookSaleProject.Data.Base;
using eBookSaleProject.Data.Enum;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading;

namespace eBookSaleProject.Models
{
    public class Book:IEntityBase
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public double Price { get; set; }

        [NotMapped]
        public IFormFile ImageUpload { get; set; }

        public byte[] Image { get; set; }

        [NotMapped]
        public IFormFile BookFileUpload { get; set; }

        public byte[] BookFile { get; set; }

        public DateTime EdititonDate { get; set; }

        public BookCategory BookCategory { get; set; }

        // Relationships
        public List<Author_Book> Author_Books { get; set; }

        //Publisher
        public int PublisherId { get; set; }

        [ForeignKey("PublisherId")]
        public Publisher Publisher { get; set; }
    }
}

eBookSaleProject/Controllers/AuthorController.cs
using eBookSaleProject.Data;
using eBookSaleProject.Data.Services;
using eBookSaleProject.Data.Static;
using eBookSaleProject.Models;
using eBookSaleProject.Models.PaginationModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace eBookSaleProject.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class AuthorController : Controller
    {
        private readonly IAuthorService authorService;

        public AuthorController(IAuthorService authorService)
        {
            this.authorService = authorService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(int pg = 1)
        {
          var allAuthors = await authorService.GetAllAsync();
            const int pageSize = 9;
            if (pg < 1)
            {
                pg = 1;
            }

            int rescCount = allAuthors.Count();

            var paginationModel = new PaginationModel(rescCount, pg, pageSize);

            int rescSkip = (pg - 1) * pageSize;

            var data = allAuthors.Skip(rescSkip).Take(paginationModel.PageSize).ToArray();
            this.ViewBag.PaginationModel = paginationModel;

            return View(data);
            //return View(allAuthors);

        }


        [AllowAnonymous]
        public async Task<FileResult> AuthorImage(int id)
        {

            Author author = await authorService.GetByIdAsync(id);
            if (author != null && author.Image?.Length > 0)
            {
                return File(author.Image, "image/jpeg", author.FullName + "-" + author.Id + ".jpg");
            }
            return null;
        }

        //Get:  Author/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }



        //Get:Author/Details/new{ id = author.id}
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var authorDetails = await authorService.GetByIdAsync(id);
            if(authorDetails == null)
            {
                return View(nameof(NotFound));
            }
            return View(authorDetails);
        }

        //Get: Author/Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var authorDetails = await authorService.GetByIdAsync(id);
            if (authorDetails == null) return View("NotFound");
            
            return View(authorDetails);

        }

        //Get: Author/Delete
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var author = await authorService.GetByIdAsync(id); 
            if(author==null)
            {
                return View(nameof(NotFound));
            }
            return View(author);
        }

        //Post: Author/Delete
        [HttpPost]
        public async Task<IActionResult> DeleteAuthor(int id)
        {
            var author = await authorService.GetByIdAsync(id);
            if(author == null)
            {
                return View(nameof(NotFound));
            }
            await authorService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        //Post: Author/Create
        [HttpPost]
        public async Task<IActionResult> Create(Author author, IFormFile ImageUpload)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }
            using(var stream =new MemoryStream())
            {
               await ImageUpload.CopyToAsync(stream);
                author.Image = stream.ToArray();
            }
            await authorService.AddAsync(author);
            return RedirectToAction(nameof(Index));
        }

        //Post: Author/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(int id,  Author author, IFormFile ImageUpload)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }
            if(ImageUpload != null)
            {
                using (var stream = new MemoryStream())
                {
                    await ImageUpload.CopyToAsync(stream);
                    author.Image = stream.ToArray();
                }
            }
            await authorService.UpdateAsync(id, author);
            return RedirectToAction("Index");
        }

        
    }
}

eBookSaleProject/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using eBookSaleProject.Data.Services;
using eBookSaleProject.Data.Cart;
using eBookSaleProject.Data.ViewModels;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace eBookSaleProject.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IBookService bookService;
        private readonly ShoppingCart shoppingCart;
        private readonly IOrdersService ordersService;

        public OrdersController(IBookService bookService, ShoppingCart shoppingCart,IOrdersService ordersService)
        {
            this.bookService = bookService;
            this.shoppingCart = shoppingCart;
            this.ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await ordersService.GetOrdersByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }

        public async Task<IActionResult> MyBooks()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var books = await ordersService.GetOrderedBooksByUserIdAndRoleAsync(userId, userRole);
            return View(books);
        }

        public IActionResult ShoppingCart()
        {
            var items = shoppingCart.GetShoppingCartItems();
            shoppingCart.ShoppingCartItems = items;
            var response = new ShoppingCartViewModel()
            {
                ShoppingCart = shoppingCart,
                ShoppingCartTotal = shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item =await bookService.GetBookByIdAsync(id);
            if(item != null)
            {
                shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await bookService.GetBookByIdAsync(id);
            if (item != null)
            {
                shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = shoppingCart.GetShoppingCartItems();

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await  ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await shoppingCart.ClearShoppingCartAsync();
            shoppingCart.ShoppingCartItems = null;
            return View("OrderCompleted");
        }

    }
}

eBookSaleProject/Controllers/PublisherController.cs
using Microsoft.AspNetCore.Mvc;
using eBookSaleProject.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using eBookSaleProject.Data.Services;
using eBookSaleProject.Models;
using Microsoft.AspNetCore.Authorization;
using eBookSaleProject.Data.Static;
using Microsoft.AspNetCore.Http;
using System.IO;
using eBookSaleProject.Models.PaginationModel;

namespace eBookSaleProject.Controllers
{
    [Authorize (Roles = UserRoles.Admin)]
    public class PublisherController : Controller
    {
        private readonly IPublisherService publisherService;

        public PublisherController( IPublisherService publisherService)
        {
            this.publisherService = publisherService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(int pg = 1)
        {
            var allPublishers = await publisherService.GetAllAsync();
            const int pageSize = 9;
            if (pg < 1)
            {
                pg = 1;
            }

            int rescCount = allPublishers.Count();

            var paginationModel = new PaginationModel(rescCount, pg, pageSize);

            int rescSkip = (pg - 1) * pageSize;

            var data = allPublishers.Skip(rescSkip).Take(paginationModel.PageSize).ToArray();
            this.ViewBag.PaginationModel = paginationModel;
           
            return View(data);
           // return View(allPublishers);
        }

        //Get: Details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var publisherDetails = await publisherService.GetByIdAsync(id);
            if(publisherDetails == null)
            {
                return View(nameof(NotFound));
            }
            return View(publisherDetails);
        }

        //Get: Create

        public IActionResult Create()
        {
            return View();
        }

        //Post: Create
        [HttpPost]
        public async Task<IActionResult> Create( Publisher publisher, IFormFile LogoUpload)
        {
            if (!ModelState.IsValid)
            {
                return View(publisher);
            }
            using(var stream = new MemoryStream())
            {
               await LogoUpload.CopyToAsync(stream);
               publisher.Logo = stream.ToArray();
            }
            await publisherService.AddAsync(publisher);
            return RedirectToAction(nameof(Index));
        }



        //Get: Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var publisherDetails = await publisherService.GetByIdAsync(id);
            if(publisherDetails == null)
            {
                return View(nameof(NotFound));
            }
            return View(publisherDetails);
        }


        [AllowAnonymous]
        public async Task<FileResult> LogoImage(int id)
        {

            Publisher publisher = await publisherService.GetByIdAsync(id);
            if (publisher != null && publisher.Logo?.Length > 0)
            {
                return File(publisher.Logo, "image/jpeg", publisher.Logo + "-" + publisher.Id + ".jpg");
            }
            return null;
        }


        //Post: Edit
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Publisher publisher, IFormFile LogoUpload)
        {

            if (!ModelState.IsValid)
            {
                return View(publisher);
            }
            using (var stream = new MemoryStream())
            {
                await LogoUpload.CopyToAsync(stream);
                publisher.Logo = stream.ToArray();
            }
            await publisherService.UpdateAsync(id, publisher);
            return RedirectToAction(nameof(Index));
        }

        //Get: Publisher/Delete
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var author = await publisherService.GetByIdAsync(id);
            if (author == null)
            {
                return View(nameof(NotFound));
            }
            return View(author);
        }

        //Post: Publisher/Delete
        [HttpPost]
        public async Task<IActionResult> DeleteAuthor(int id)
        {
            var author = await publisherService.GetByIdAsync(id);
            if (author == null)
            {
                return View(nameof(NotFound));
            }
            await publisherService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eBookSaleProject/Views/Book/Create.cshtml
@model BookViewModel
@using eBookSaleProject.Data.Enum;
@{
    ViewBag.Title = "Create New Book";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create New Book</h4>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control-range" min="0" step="0.5"/>
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageUpload" class="control-label"></label>
                                    <div class = "custom-file">
                                        <input  asp-for="ImageUpload" class="form-control" type="file" accept="image/*" />
                                    </div>
                                <span asp-validation-for="ImageUpload" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="BookFileUpload" class="control-label"></label>
                                    <div class = "custom-file">
                                        <input  asp-for="BookFileUpload" class="form-control" type="file"  />
                                    </div>
                                <span asp-validation-for="BookFileUpload" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="EdititonDate" class="control-label"></label>
                                <input asp-for="EdititonDate" type="date" class="form-control"/>
                                <span asp-validation-for="EdititonDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="BookCategory" class="control-label"></label>
                                <select asp-for="BookCategory" class="form-control" asp-items="Html.GetEnumSelectList<BookCategory>()"></select> 
                                <span asp-validation-for="BookCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PublisherId" class="control-label"></label>
                                <select asp-for="PublisherId" class="form-control" asp-items ="ViewBag.PublishersList"></select> 
                                <span asp-validation-for="PublisherId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="AuthorIds" class="control-label"></label>
                                <select asp-for="AuthorIds" class="form-control" asp-items ="ViewBag.AuthorsList" multiple></select>
                                <span asp-validation-for="AuthorIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
       $("#ImageUpload").on("change",function(){
        var output = document.getElementById('ImageUrlPreview');
        output.src = $(this).val()
        });
    </script>
}

eBookSaleProject/Views/Book/Details.cshtml
@model Book
@{
    ViewBag.Title = "Details of Authors";
}

<div class="row">

    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="/Book/BookImage/@Model.Id" width="100%" height="80%" alt="">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Publisher:</b>
                            <a asp-controller="Publisher" asp-action="Details" asp-route-id="@Model.PublisherId">@Model.Publisher.Name</a>
                        </p>
                        <p class="card-text"> <b>Category:</b> @Model.BookCategory.ToString()</p>
                        <p class="card-text"> <b>Edition Date:</b> @Model.EdititonDate.ToString("yyyy MMMM")</p>
                        <p class="card-text">
                            <b>Status:</b>
                            @if (DateTime.Now - @Model.EdititonDate >= TimeSpan.FromDays(3))
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else
                            {
                                <span class="badge bg-info text-white">SOON</span>

                            }
                        </p>
                        <p class="card-tex">
                            <b>Authors: </b>
                            <hr />
                            <div class="row">
                                @foreach (var author_Book in Model.Author_Books)
                                {
                                    <div class="column text-center">
                                        <img class="border-info rounded-circle" src="/Author/AuthorImage/@author_Book.Author.Id" style="max-width:200px" />
                                        <br />
                                        <a asp-controller="Author" asp-action="Details" asp-route-id="@author_Book.AuthorId">@author_Book.Author.FullName</a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-rigth" asp-action="Index">
                                <i class="bi bi-eye-fill"></i>
                                Back To List
                            </a>
                            <a class="btn btn-success text-white @((DateTime.Now - @Model.EdititonDate >= TimeSpan.FromDays(200)) ? "":"disabled")"
                               asp-controller="Orders" asp-action="AddItemToShoppingCart"
                               asp-route-id="@Model.Id">
                                <i class="bi bi-cart-plus"></i>Add To Cart ($@Model.Price.ToString())
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

eBookSaleProject/Views/Book/Edit.cshtml
@model BookViewModel
@using eBookSaleProject.Data.Enum;
@{
    ViewBag.Title = "Update Book";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Update Book</h4>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control-range" min="0" step="0.5"/>
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageUpload" class="control-label"></label>
                                    <div class="custom-file">
                                        <input asp-for="ImageUpload" class="form-control" type="file" accept="image/*" />
                                    </div>
                                <span asp-validation-for="ImageUpload" class="text-danger"></span>
                            </div>
                             <div class="form-group">
                                <label asp-for="BookFileUpload" class="control-label"></label>
                                    <div class = "custom-file">
                                        <input  asp-for="BookFileUpload" class="form-control" type="file" accept="image/*" />
                                    </div>
                                <span asp-validation-for="BookFileUpload" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="EdititonDate" class="control-label"></label>
                                <input asp-for="EdititonDate" type="date" class="form-control"/>
                                <span asp-validation-for="EdititonDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="BookCategory" class="control-label"></label>
                                <select asp-for="BookCategory" class="form-control" asp-items="Html.GetEnumSelectList<BookCategory>()"></select> 
                                <span asp-validation-for="BookCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PublisherId" class="control-label"></label>
                                <select asp-for="PublisherId" class="form-control" asp-items ="ViewBag.PublishersList"></select> 
                                <span asp-validation-for="PublisherId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="AuthorIds" class="control-label"></label>
                                <select asp-for="AuthorIds" class="form-control" asp-items ="ViewBag.AuthorsList" multiple></select>
                                <span asp-validation-for="AuthorIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function(){
         var output = document.getElementById("ImageUrlPreview");
        output.src = $("#ImageUpload").val()
        });
       $("#ImageUpload").on("change",function(){
        var output = document.getElementById("ImageUrlPreview");
        output.src = $(this).val()
        });
    </script>
}

eBookSaleProject/Views/Book/Index.cshtml
@model IEnumerable<Book>
@{
    ViewBag.Title = "List fo Books";
}

<div class="row">
    @foreach (var item in Model)
    {

        <div class="col-md-4 col-xs-6 border-primary md-3" style="padding:10px">
            <div class="card mb-3 d-flex flex-column" style="max-width:540px; height:100%;">

                <div class="card-header text-white bg-info">
                    <p class="card-text">
                        <h5 class="card-title">
                            @item.Name
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id">
                                    <i class="bi bi-pencil-square"></i>
                                </a>
                            }
                        </h5>
                    </p>
                </div>

                <div class="row g-0">
                    <div class="col-md-6">
                        <img src="/Book/BookImage/@item.Id" width="100%" height="100%" alt="">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"> <b>Publisher:</b> @item.Publisher.Name</p>
                            <p class="card-text"> <b>Category:</b> @item.BookCategory.ToString()</p>
                            <p class="card-text"> <b>Edition Date:</b> @item.EdititonDate.ToString("yyyy MMMM")</p>
                            <p class="card-text">
                                <b>Status:</b>
                                @if (DateTime.Now - @item.EdititonDate >= TimeSpan.FromDays(200))
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else
                                {
                                    <span class="badge bg-info text-white">SOON</span>
                                }
                            </p>
                        </div>
                    </div>
                </div>

                <div class="card-footer mt-auto">
                    <p class="card-text">
                        <a class="btn btn-outline-primary float-rigth" asp-action="Details" asp-route-id="@item.Id">
                            <i class="bi bi-eye-fill">
                            </i>Show Details
                        </a>
                        <a class="btn btn-success text-white @((DateTime.Now - @item.EdititonDate >= TimeSpan.FromDays(200)) ? "":"disabled")"
                       asp-controller="Orders" asp-action="AddItemToShoppingCart"
                       asp-route-id="@item.Id">
                            <i class="bi bi-cart-plus"></i>Add To Cart ($ @item.Price.ToString())
                        </a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>

@await Html.PartialAsync("_Pagination","Book")

@await Html.PartialAsync("_CreateItem","Book")